version: '3'
services:
  app:
    restart:  on-failure
    build: 
      context: .
      dockerfile: Dockerfile.prod
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: npm start
  postgres:
    image: 'postgres'
    ports:
      - '5432:5432'
    volumes:
      - database:/var/lib/postgresql/data
    env_file:
      - ./postgres.db.env

