version: '3'
services:
  db:
    image: 'postgres'
    ports:
      - '5432:5432'
    expose:
      - "5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: risedb

  redis_cache:
    image: 'redis:alpine'
    command: redis-server
    ports:
      - '6379:6379'
    environment:
      - REDIS_REPLICATION_MODE=master

  app:
    restart:  on-failure
    build: 
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      - db
      - redis_cache
    env_file:
      - .env
    expose:
      - "8000"
    ports:
      - "8000:8000"
    command: npm run start:dev
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
      

