import dotenv from "dotenv";

dotenv.config();

export default {
  PORT: 8000,
  DATABASE_HOST: process.env.DATABASE_HOST,
  DATABASE_NAME: process.env.DATABASE_NAME,
  DATABASE_PASSWORD: process.env.DATABASE_PASSWORD,
  DATABASE_USER: process.env.DATABASE_USER,
  DATABASE_PORT: process.env.DATABASE_PORT,
  DATABASE_ENABLE_LOGGING: process.env.DATABASE_ENABLE_LOGGING,
  DATABASE_ENABLE_SYNC: process.env.DATABASE_ENABLE_SYNC,
  DATABASE_CONNECT_RETRY_COUNT: process.env.DATABASE_CONNECT_RETRY_COUNT,
  DATABASE_CONNECT_RETRY_INTERVAL_MS:
    process.env.DATABASE_CONNECT_RETRY_INTERVAL_MS,
  AWS_ACCESS_KEY: process.env.AWS_ACCESS_KEY,
  AWS_ACCESS_SECRET: process.env.AWS_ACCESS_SECRET,
  AWS_REGION: process.env.AWS_REGION,
  AWS_S3_BUCKET_NAME: process.env.AWS_S3_BUCKET_NAME,
  jwtSecret: process.env.JWT_SECRET,
};
